/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

/**
 *
 * @author LaWebStore
 */
public class PanelTitulo extends javax.swing.JPanel {

    /**
     * Creates new form PanelTitulo
     */
    public PanelTitulo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lbl_titulo = new javax.swing.JLabel();
        lbl_tipoTitulo = new javax.swing.JLabel();
        lbl_fechaObtencion = new javax.swing.JLabel();
        lbl_categoria = new javax.swing.JLabel();
        date_fechaObtencion = new javax.swing.JFormattedTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jComboBox3 = new javax.swing.JComboBox();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setMaximumSize(new java.awt.Dimension(500, 270));
        setMinimumSize(new java.awt.Dimension(499, 269));
        setPreferredSize(new java.awt.Dimension(500, 270));
        setLayout(null);

        lbl_titulo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_titulo.setText("Título:");
        add(lbl_titulo);
        lbl_titulo.setBounds(10, 30, 120, 14);

        lbl_tipoTitulo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_tipoTitulo.setText("Tipo Título:");
        add(lbl_tipoTitulo);
        lbl_tipoTitulo.setBounds(30, 70, 100, 14);

        lbl_fechaObtencion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_fechaObtencion.setText("Fecha de Obtención:");
        add(lbl_fechaObtencion);
        lbl_fechaObtencion.setBounds(10, 110, 120, 14);

        lbl_categoria.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_categoria.setText("Categoría:");
        add(lbl_categoria);
        lbl_categoria.setBounds(270, 70, 70, 14);

        date_fechaObtencion.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        date_fechaObtencion.setText("dd/mm/yyyy");
        add(date_fechaObtencion);
        date_fechaObtencion.setBounds(150, 105, 130, 20);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Titulo", "Tipo Titulo", "Fecha Obtencion", "Categoria"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        add(jScrollPane2);
        jScrollPane2.setBounds(30, 140, 420, 90);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ingeniería en sistemas de información", "Item 2", "Item 3", "Item 4" }));
        add(jComboBox1);
        jComboBox1.setBounds(145, 25, 300, 20);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ingeniería", "Licenciatura", "Tecnicatura", " " }));
        add(jComboBox2);
        jComboBox2.setBounds(145, 65, 130, 20);

        jButton1.setText("Agregar");
        add(jButton1);
        jButton1.setBounds(370, 105, 80, 23);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Categoría 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBox3);
        jComboBox3.setBounds(350, 65, 95, 20);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField date_fechaObtencion;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lbl_categoria;
    private javax.swing.JLabel lbl_fechaObtencion;
    private javax.swing.JLabel lbl_tipoTitulo;
    private javax.swing.JLabel lbl_titulo;
    // End of variables declaration//GEN-END:variables
}
