/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

/**
 *
 * @author LaWebStore
 */
public class PanelFacultad extends javax.swing.JPanel {

    /**
     * Creates new form Panel2
     */
    public PanelFacultad() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_facultad = new javax.swing.JLabel();
        lbl_universidad = new javax.swing.JLabel();
        lbl_centroInv = new javax.swing.JLabel();
        lbl_grupoInv = new javax.swing.JLabel();
        lbl_ciudad = new javax.swing.JLabel();
        lbl_provincia = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jComboBox4 = new javax.swing.JComboBox();
        jComboBox5 = new javax.swing.JComboBox();
        jComboBox6 = new javax.swing.JComboBox();

        setMaximumSize(new java.awt.Dimension(500, 270));
        setMinimumSize(new java.awt.Dimension(500, 270));
        setPreferredSize(new java.awt.Dimension(500, 270));
        setLayout(null);

        lbl_facultad.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_facultad.setText("Facultad:");
        add(lbl_facultad);
        lbl_facultad.setBounds(10, 70, 140, 14);

        lbl_universidad.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_universidad.setText("Universidad:");
        add(lbl_universidad);
        lbl_universidad.setBounds(10, 30, 140, 14);

        lbl_centroInv.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_centroInv.setText("Centro de Investigación:");
        add(lbl_centroInv);
        lbl_centroInv.setBounds(10, 110, 140, 14);

        lbl_grupoInv.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_grupoInv.setText("Grupo de Investigación:");
        add(lbl_grupoInv);
        lbl_grupoInv.setBounds(10, 150, 140, 14);

        lbl_ciudad.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_ciudad.setText("Ciudad:");
        add(lbl_ciudad);
        lbl_ciudad.setBounds(10, 190, 140, 14);

        lbl_provincia.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_provincia.setText("Provincia");
        add(lbl_provincia);
        lbl_provincia.setBounds(10, 230, 140, 14);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBox1);
        jComboBox1.setBounds(180, 185, 250, 20);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBox2);
        jComboBox2.setBounds(180, 25, 250, 20);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBox3);
        jComboBox3.setBounds(180, 65, 250, 20);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBox4);
        jComboBox4.setBounds(180, 145, 250, 20);

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBox5);
        jComboBox5.setBounds(180, 105, 250, 20);

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBox6);
        jComboBox6.setBounds(180, 225, 250, 20);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JComboBox jComboBox6;
    private javax.swing.JLabel lbl_centroInv;
    private javax.swing.JLabel lbl_ciudad;
    private javax.swing.JLabel lbl_facultad;
    private javax.swing.JLabel lbl_grupoInv;
    private javax.swing.JLabel lbl_provincia;
    private javax.swing.JLabel lbl_universidad;
    // End of variables declaration//GEN-END:variables
}
